
name: advanced_html_to_pdf
description: A Flutter package to easily convert HTML content into high-quality PDF documents.
version: 0.0.1
homepage: https://github.com/1morecode/advanced_html_to_pdf
repository: https://github.com/1morecode/advanced_html_to_pdf
issue_tracker: https://github.com/1morecode/advanced_html_to_pdf/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.14.2
  pdf: ^3.11.3
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
